apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: default
  labels:
    app: api-gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: admin
    port: 8081
    targetPort: admin
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: default
  labels:
    app: api-gateway
automountServiceAccountToken: false