apiVersion: v1
kind: Service
metadata:
  name: api-generation
  namespace: default
  labels:
    app: api-generation
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: api-generation
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-generation
  namespace: default
  labels:
    app: api-generation
automountServiceAccountToken: false