apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mercurious-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
    storage:
      type: persistent-claim
      size: 100Gi
      class: local-path
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1000m
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      class: local-path
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: mercurious-app-user
  namespace: kafka
  labels:
    strimzi.io/cluster: mercurious-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Producer permissions
      - resource:
          type: topic
          name: "*"
        operations:
          - Write
          - Create
          - Describe
      - resource:
          type: cluster
        operations:
          - Create
      # Consumer permissions
      - resource:
          type: topic
          name: "*"
        operations:
          - Read
          - Describe
      - resource:
          type: group
          name: "*"
        operations:
          - Read
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: api-events
  namespace: kafka
  labels:
    strimzi.io/cluster: mercurious-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    segment.ms: 86400000     # 1 day